<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
		<OutputPath>..\..\Build\Bots</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
		<OutputPath>..\..\Build\Bots</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	</PropertyGroup>
	
  <ItemGroup>
    <Compile Include="EastBankFsTrader.fs" />
    <Compile Include="Library.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Source\NasdaqTrader.Bot.Core\NasdaqTrader.Bot.Core.csproj" />
  </ItemGroup>

</Project>
